### ISSUE TITLE
Hosting Service

### ISSUE THREAD

**Issue by eCurrency** [eCurrency/peatio#2]
Ok,
We'd like to use a hosting company that allows us to start off with a VPS to get accustomed to things, and then switch over the dedicated servers.

RIght now we have accounts with Leaseweb.com

Has anyone found that there are some better initial Server Type/Parameters/Features than suggested in the Peatio Documentation?

e

**Comment by tawandakembo** [comment]
I run a Bitcoin Exchange that is a Peatio fork (but I've taken it into an entirely different direction). I use AWS for hosting and I would highly reccomend we host of AWS. Some Server Type/Parameter/Features I've changed are:
- Decoupling the servers - MySQL is running on it's own instance (an RDS instance), The rails code on it's own instance, Redis is running on it's own instance (an ElastiCache instance),  and bitocind is running on it's own instance. The advantage of this is that as the exchange grows, it's not just the whole server that should be upgraded and different components scale at different rates. Decoupling services allows you to scale different components as and when they need to grow. It also has security benefits too - if someone hacks into my main server, they don't have access to the other servers because they are in different security groups (AWS makes it easier to manage security groups.
- I replaced bitcoind with bitgod to have a more secure bitcoin wallet. If you use bitcoind and someone hacks into the server that is running the bitcoind daemon, they can steal all your bitcoins. That's a very big weakness in peatio. This doesn't even need to be a hacker, it could be an employee. Bitgod is a drop-in replacement for bitcoind that is released by BitGo. It allows you to turn your bitcoin wallet into a multisig wallet (different people can sign bitcoin transactions before they leave the wallet) and you can programatically put in certain rules regarding how you want transactions to work. Some examples of some rules we've put are, bitcoin transactions can only be automatically signed if they originate from one and only one public IP address and if they are below a certain limit.

Those are the few ones I can think of. 

I can see you needed me earlier but I wasn't really available. I'm online most of today if you need me (what time zone are you in? I'm in CAT)

**Comment by netwareboss** [comment]
I live in Asia ^^

2016-01-10 13:20 GMT+08:00 Tawanda Kembo notifications@github.com:

**Comment by tawandakembo** [comment]
![image](https://cloud.githubusercontent.com/assets/1892654/12220157/2b3c65fa-b76c-11e5-850d-be53275ca2f3.png)

**Comment by tawandakembo** [comment]
Just wanted to know how different your time will be from mine to see if we can work during the day. We really didn't get a chance to discuss the scope of work (it will be fairly quick and easy for me to set up a Peatio installation if that's all that needs to be done), the timelines (when do you think the project will start? it will be good so that I can plan my time and avail myself when/if needed), Is there going to be any fiancial compensation for our time (if so, how much), Are we committing to providing support in the long term (I notice from the other conversations that you're doing this for a client not yourself). I'm also available to chat on Skype, Google hangout or Gitter if you prefer that.

**Comment by netwareboss** [comment]
so ..... can we use the x-coins.com for globa domain name???
I own this domain name for a long time^^
or other good choise????

2016-01-10 13:38 GMT+08:00 Tawanda Kembo <notifications@github.com>:

**Comment by tkembo** [comment]
x-coins.com sounds great. 

When you had a chance to think about it, it will be great if you can answer the questions I asked above. Your responses will allow me to estimate how much I can commit myself - which is what you need right?

**Comment by netwareboss** [comment]
we can start the project right now^^

2016-01-10 14:00 GMT+08:00 Tawanda Kembo <notifications@github.com>:

**Comment by tawandakembo** [comment]
Ok. & the other questions?
- What's the scope of work? What exactly needs to be done? Is it just a Peatio installation?
- Is there going to be any financial compensation for my time? How much? What are the payment terms.
- Are you the one who will support the exchange when it's deployed or do you expect me to continue to do that?

I would like to be clear about all these before we start. I'm ready to start now but I want us to be  clear on all of those first.

**Comment by netwareboss** [comment]
1.Depend what you can do.
2.I can pay you bitcoin
3.I will support no matter money or skills or time........

2016-01-10 14:27 GMT+08:00 Tawanda Kembo <notifications@github.com>:

**Comment by tkembo** [comment]
1. So what exactly do you want done? & I'll let  you know which of that I can do.

**Comment by tkembo** [comment]
Do you want to have this conversation on Skype instead?

**Comment by tkembo** [comment]
I'm going out. I'm heading to the gymn so I will be away (and offline) for about 2 hours. We can pick this up when I get back.

**Comment by netwareboss** [comment]
my skype: borchnew

2016-01-10 14:57 GMT+08:00 Tawanda Kembo notifications@github.com:

**Comment by netwareboss** [comment]
i don't think bitgo is good idea^^
because we only have very few bitcoins in hot wallet!!!
we will use multi sign to protect cool wallet!!
we only forcus on security of Database!!
this is my opinion^^

2016-01-10 15:01 GMT+08:00 Josh netwareboss@gmail.com:

**Comment by tawandakembo** [comment]
I'm back. & I've just sent you a request on Skype

**Comment by eCurrency** [comment]
Hey @netwareboss,

C'mon guys.

This thread is for me and my clients project. You answered me saying that you could help, and so did tkembo, and now you two have basically used my thread here to work out details of your own plans.

@tkembo, you said you would assist, and I waited for a reply and assumed you were no longer interested. 

This was not what I set this up for and it was not expected.

Good luck to you guys, but I'm afraid I'm going to have to moderate whats under this account in the direction towards what I am working on...

e

**Comment by tawandakembo** [comment]
@eCurrency sorry about that. All this time, I actually thought I was talking to you. Sorry.

**Comment by tawandakembo** [comment]
@eCurrency you can still delete our comments. Again sorry.

**Comment by eCurrency** [comment]
@tkembo 
lol - after re-reading the messages I started to realize that maybe you thought @netwareboss was me. Netwareboss!!! You devil! ;)

Yeah, @tkembo I'm the guy who thought it was a cool coincidence (sign!) that you had the same 1st name as my cousin in the U.S. (Who I have not seen in a long long long time).

So anyway, I was a little disappointed thinking "back to the drawing board".

Well, I've been up all night, it's 5am Sunday here for me, and I need to get some sleep so I can get up and watch some sports! (well, and do some work too).

It looks like you added me to the skype group @netwareboss. Ok, I'll catch up with you guys after I get some rest and we get our times synchronized.

Oh, to answer your questions:

You asked:
What's the scope of work? What exactly needs to be done? Is it just a Peatio installation?

Answer:
- Basically. To get it operating, secure and tested.

You asked:
Is there going to be any financial compensation for my time? How much? What are the payment terms.

Answer:
- I'd like to get creative on the compensation. 
- I'd like to hold on to as much funds as possible, so I'm hoping to find someone interested in an equity position
- I'm new to project management and this is on of my 1st projects, and THE 1st project like this working with others, I'm not sure where to start. 
- I'd like to hear your thoughts on compensation.
- I want to build a team. As many dedicated, enthusiastic, creative, and talented volunteers as possible

You asked:
Are you the one who will support the exchange when it's deployed or do you expect me to continue to do that?
- I'll be forming and administering a Team if you wish to be a Leader in or just a part of it.

e

**Comment by eCurrency** [comment]
Please see https://github.com/eCurrency/peatio01/issues/1/ for continuation of this project.
